spring:
  application:
    name: person
  profiles:
    active: local
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,keepalive